language: java
jdk:
  - openjdk18

branches:
  only:
    - main

before_install:
  - "chmod +x gradlew"

#Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r test-springboot2-webservice *
  - mkdir -p deploy
  - mv test-springboot2-webservice.zip deploy/test-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-springboot-build-soo
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-springboot-build-soo
    key: test-springboot2-webservice.zip
    bundle_type: zip
    application: test-springboot2-webservice
    deployment_group: test-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - book0256@naver.com